# Generated by Django 6.0.3 on 2026-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
